# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daria/Projects/lab7.1/CreateFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateFile(object):
    def setupUi(self, CreateFile):
        CreateFile.setObjectName("CreateFile")
        CreateFile.resize(281, 147)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateFile)
        self.buttonBox.setGeometry(QtCore.QRect(-120, 110, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(CreateFile)
        self.label.setGeometry(QtCore.QRect(30, 30, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CreateFile)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 101, 17))
        self.label_2.setObjectName("label_2")
        self.filename = QtWidgets.QLineEdit(CreateFile)
        self.filename.setGeometry(QtCore.QRect(130, 30, 113, 21))
        self.filename.setObjectName("filename")
        self.filesize = QtWidgets.QLineEdit(CreateFile)
        self.filesize.setGeometry(QtCore.QRect(130, 60, 113, 21))
        self.filesize.setObjectName("filesize")

        self.retranslateUi(CreateFile)
        self.buttonBox.accepted.connect(CreateFile.accept) # type: ignore
        self.buttonBox.rejected.connect(CreateFile.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreateFile)

    def retranslateUi(self, CreateFile):
        _translate = QtCore.QCoreApplication.translate
        CreateFile.setWindowTitle(_translate("CreateFile", "Create File"))
        self.label.setText(_translate("CreateFile", "File name:"))
        self.label_2.setText(_translate("CreateFile", "File size (Kb):"))
