# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daria/Projects/lab7.1/DeleteFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteFile(object):
    def setupUi(self, DeleteFile):
        DeleteFile.setObjectName("DeleteFile")
        DeleteFile.resize(256, 126)
        self.buttonBox = QtWidgets.QDialogButtonBox(DeleteFile)
        self.buttonBox.setGeometry(QtCore.QRect(-130, 90, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(DeleteFile)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 17))
        self.label.setObjectName("label")
        self.filename = QtWidgets.QLineEdit(DeleteFile)
        self.filename.setGeometry(QtCore.QRect(110, 30, 113, 21))
        self.filename.setObjectName("filename")

        self.retranslateUi(DeleteFile)
        self.buttonBox.accepted.connect(DeleteFile.accept) # type: ignore
        self.buttonBox.rejected.connect(DeleteFile.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DeleteFile)

    def retranslateUi(self, DeleteFile):
        _translate = QtCore.QCoreApplication.translate
        DeleteFile.setWindowTitle(_translate("DeleteFile", "DeleteFle"))
        self.label.setText(_translate("DeleteFile", "File name:"))
