# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daria/Projects/lab7.1/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 41, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelDiskName = QtWidgets.QLabel(self.centralwidget)
        self.labelDiskName.setGeometry(QtCore.QRect(60, 20, 71, 17))
        self.labelDiskName.setObjectName("labelDiskName")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 20, 121, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 20, 67, 17))
        self.label_3.setObjectName("label_3")
        self.labelDiskFreeSize = QtWidgets.QLabel(self.centralwidget)
        self.labelDiskFreeSize.setGeometry(QtCore.QRect(340, 20, 151, 17))
        self.labelDiskFreeSize.setObjectName("labelDiskFreeSize")
        self.pushButtonCreateFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCreateFile.setGeometry(QtCore.QRect(150, 690, 121, 25))
        self.pushButtonCreateFile.setObjectName("pushButtonCreateFile")
        self.pushButtonDeleteFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteFile.setGeometry(QtCore.QRect(460, 690, 121, 25))
        self.pushButtonDeleteFile.setObjectName("pushButtonDeleteFile")
        self.pushButtonDeleteAllFiles = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteAllFiles.setGeometry(QtCore.QRect(760, 690, 141, 25))
        self.pushButtonDeleteAllFiles.setObjectName("pushButtonDeleteAllFiles")
        self.tableDiskView = QtWidgets.QTableWidget(self.centralwidget)
        self.tableDiskView.setGeometry(QtCore.QRect(20, 40, 1061, 641))
        self.tableDiskView.setObjectName("tableDiskView")
        self.tableDiskView.setColumnCount(0)
        self.tableDiskView.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab 7: Disk Operations"))
        self.label.setText(_translate("MainWindow", "Disk:"))
        self.labelDiskName.setText(_translate("MainWindow", "labelDiskName"))
        self.label_2.setText(_translate("MainWindow", "Total size: 360 Kb"))
        self.label_3.setText(_translate("MainWindow", "Free size:"))
        self.labelDiskFreeSize.setText(_translate("MainWindow", "labelDiskFreeSize"))
        self.pushButtonCreateFile.setText(_translate("MainWindow", "Create File"))
        self.pushButtonDeleteFile.setText(_translate("MainWindow", "Delete File"))
        self.pushButtonDeleteAllFiles.setText(_translate("MainWindow", "Delete All Files"))
